name: FakeEntityLib
version: ${project.version}
description: "Creates fake entites that are managed off the main server thread"
author: "Lewys Davies (Lew_)"
depends: ProtocolLib
main: uk.lewdev.entitylib.FakeEntityPlugin
api-version: 1.17